FROM python:3.13-slim

WORKDIR /app

COPY Pipfile Pipfile.lock database.sh ./
COPY docs/ /app/docs/
COPY public/ /app/public/

RUN pip install pipenv

RUN pipenv install --system --dev --deploy

EXPOSE 3001

CMD ["pipenv", "run", "start"]
